### ISSUE TITLE
[BUG] sync keeps going after turning off

### ISSUE THREAD

**Issue by RakuJa** [MercurySeven/project-SSD#59]
![bug_sync](https://user-images.githubusercontent.com/48138611/116148649-75415380-a6e1-11eb-8ea8-3216aa8aa7dc.png)

**Comment by Edivad99** [comment]
In che branch?

**Comment by RakuJa** [comment]
rework branch ma non riesco a replicare il bug al momento, sarebbe da fare diversi test manuali per provare a rompere

**Comment by RakuJa** [comment]
Forse era un side effect di una cosa che ho fixato qualche commit fa, da testare se riavviene
